#pragma once

#define PBR_OUTPUT_IMAGE_COLUMNS 1280
#define PBR_OUTPUT_IMAGE_ROWS 720

#define PBR_MAX_RECURSION_DEPTH 3

#define PBR_COLOR_SKYBLUE Colorf { 0.572, 0.886, 0.992 }
#define PBR_COLOR_BLACK   Colorf { 0.0, 0.0, 0.0 }

#define PBR_BACKGROUND_COLOR PBR_COLOR_SKYBLUE
